
export default function TermsPage() {
    return (
        <main className="container mx-auto px-4 py-12 max-w-4xl">
            <h1 className="text-3xl font-bold mb-2">SILIP & TANOD - TERMS OF SERVICE</h1>
            <p className="text-sm text-muted-foreground mb-8">Effective Date: 2026-02-07</p>

            <div className="space-y-8 text-foreground">
                <section>
                    <h2 className="text-xl font-semibold mb-3">1. Acceptance of Terms</h2>
                    <p className="leading-relaxed">
                        By accessing the Silip API, the Tanod application, or downloading materials from this repository (collectively, the &quot;Services&quot;), you agree to be bound by these Terms. If you do not agree, you may not use the Services.
                    </p>
                </section>

                <section>
                    <h2 className="text-xl font-semibold mb-3">2. Nature of Services</h2>
                    <p className="leading-relaxed">
                        The Services provide a searchable knowledge base and compliance tools related to Philippine Data Privacy laws. The content includes official issuances from the National Privacy Commission (NPC).
                    </p>
                </section>

                <section>
                    <h2 className="text-xl font-semibold mb-3">3. No Legal Advice</h2>
                    <p className="leading-relaxed">
                        You acknowledge that the Services are for <strong>informational and administrative purposes only</strong>. The output generated by Silip or Tanod does not constitute legal advice. You should consult with a qualified attorney for advice on specific legal issues.
                    </p>
                </section>

                <section>
                    <h2 className="text-xl font-semibold mb-3">4. Source of Data & Intellectual Property</h2>
                    <ul className="list-disc pl-6 space-y-2">
                        <li>
                            <strong>Government Works:</strong> In accordance with <strong>Section 176.1 of Republic Act No. 8293</strong>, no copyright subsists in any work of the Government of the Philippines. The laws, rules, and issuances hosted here are public domain.
                        </li>
                        <li>
                            <strong>Platform Rights:</strong> The software, API design, database architecture, &quot;Silip&quot; and &quot;Tanod&quot; source code, and user interface are the exclusive intellectual property of <strong>Alfredo Sanchez Jr</strong>. You may not reverse engineer, scrape, or resell access to the API without express permission.
                        </li>
                    </ul>
                </section>

                <section>
                    <h2 className="text-xl font-semibold mb-3">5. Disclaimer of Warranties (&quot;As-Is&quot; Clause)</h2>
                    <p className="leading-relaxed">
                        The Services are provided &quot;AS IS&quot; and &quot;AS AVAILABLE.&quot; We strictly disclaim all warranties, whether express or implied, regarding the <strong>accuracy, currency, or completeness</strong> of the government documents provided. <strong>It is your responsibility to verify the latest issuances with the official NPC website (privacy.gov.ph).</strong>
                    </p>
                </section>

                <section>
                    <h2 className="text-xl font-semibold mb-3">6. Limitation of Liability</h2>
                    <p className="leading-relaxed">
                        To the fullest extent permitted by law, <strong>Alfredo Sanchez Jr</strong> shall not be liable for any direct, indirect, incidental, or consequential damages resulting from your use of the Services. This includes, but is not limited to, liability for data breaches, compliance fines, or legal errors resulting from reliance on this data.
                    </p>
                </section>

                <section>
                    <h2 className="text-xl font-semibold mb-3">7. Indemnification</h2>
                    <p className="leading-relaxed">
                        You agree to indemnify and hold harmless <strong>Alfredo Sanchez Jr</strong> from any claims, damages, or expenses arising from your use of the Services or your violation of these Terms.
                    </p>
                </section>

                <section>
                    <h2 className="text-xl font-semibold mb-3">8. Governing Law and Venue</h2>
                    <p className="leading-relaxed">
                        These Terms are governed by the laws of the Republic of the Philippines. Any disputes shall be resolved exclusively in the courts of <strong>Cebu City</strong>, to the exclusion of all others.
                    </p>
                </section>
            </div>
        </main>
    )
}
